<?php
/**
 * WorkflowJobsApiTest
 * PHP version 8.1
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * workflows
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.9.1rc5
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use OpenAPI\Client\Configuration;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WorkflowJobsApiTest Class Doc Comment
 *
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkflowJobsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for actionCallbackWorkflowsApiV1JobsJobIdActionCallbackPost
     *
     * Action Callback.
     *
     */
    public function testActionCallbackWorkflowsApiV1JobsJobIdActionCallbackPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createJobWorkflowsApiV1JobsPost
     *
     * Create Job.
     *
     */
    public function testCreateJobWorkflowsApiV1JobsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadJobFileWorkflowsApiV1JobsJobIdFilesFileIdGet
     *
     * Download Job File.
     *
     */
    public function testDownloadJobFileWorkflowsApiV1JobsJobIdFilesFileIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for downloadJobFilesWorkflowsApiV1JobsJobIdFilesDownloadGet
     *
     * Download Job Files.
     *
     */
    public function testDownloadJobFilesWorkflowsApiV1JobsJobIdFilesDownloadGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for executeTransitionOnJobWorkflowsApiV1JobsJobIdTransitionsTransitionIdExecutePost
     *
     * Execute Transition On Job.
     *
     */
    public function testExecuteTransitionOnJobWorkflowsApiV1JobsJobIdTransitionsTransitionIdExecutePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getJobHistoryEntryWorkflowsApiV1JobsJobIdHistoryEntryIdGet
     *
     * Get Job History Entry.
     *
     */
    public function testGetJobHistoryEntryWorkflowsApiV1JobsJobIdHistoryEntryIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getJobWorkflowsApiV1JobsJobIdGet
     *
     * Get Job.
     *
     */
    public function testGetJobWorkflowsApiV1JobsJobIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAvailableTransitionsWorkflowsApiV1JobsJobIdTransitionsGet
     *
     * List Available Transitions.
     *
     */
    public function testListAvailableTransitionsWorkflowsApiV1JobsJobIdTransitionsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listJobFilesWorkflowsApiV1JobsJobIdFilesGet
     *
     * List Job Files.
     *
     */
    public function testListJobFilesWorkflowsApiV1JobsJobIdFilesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listJobHistoryWorkflowsApiV1JobsJobIdHistoryGet
     *
     * List Job History.
     *
     */
    public function testListJobHistoryWorkflowsApiV1JobsJobIdHistoryGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listJobsWorkflowsApiV1JobsGet
     *
     * List Jobs.
     *
     */
    public function testListJobsWorkflowsApiV1JobsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plotJobHistoryWorkflowsApiV1JobsJobIdHistoryPlotGet
     *
     * Plot Job History.
     *
     */
    public function testPlotJobHistoryWorkflowsApiV1JobsJobIdHistoryPlotGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for plotJobWorkflowsApiV1JobsJobIdPlotGet
     *
     * Plot Job.
     *
     */
    public function testPlotJobWorkflowsApiV1JobsJobIdPlotGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for startJobWorkflowsApiV1JobsJobIdStartPost
     *
     * Start Job.
     *
     */
    public function testStartJobWorkflowsApiV1JobsJobIdStartPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for uploadJobFilesWorkflowsApiV1JobsJobIdFilesPost
     *
     * Upload Job Files.
     *
     */
    public function testUploadJobFilesWorkflowsApiV1JobsJobIdFilesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
